version: "3"

services:
  proxy:
    image: nginx:1-alpine
    ports:
      # only ports facing any connection from outside
      - 172.17.0.1:6580:80
      # - 1236:1236
      # - 8536:8536
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
      # setup your certbot and letsencrypt config
      # - ./certbot:/var/www/certbot
      # - ./letsencrypt:/etc/letsencrypt/live
    restart: always
    depends_on:
      - pictrs
      - web

  lemmy:
    image: dessalines/lemmy:${LEMMY_VERSION_TAG}
    hostname: lemmy
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
    depends_on:
      - postgres
      - pictrs

  pictrs:
    image: asonix/pictrs:0.5.16
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    environment:
      - PICTRS__API_KEY=${API_KEY}
      - RUST_BACKTRACE=full
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
    user: 991:991
    volumes:
      - ./pictrs:/mnt
    restart: always

  postgres:
    image: postgres:15-alpine
    # this needs to match the database host in lemmy.hson
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=lemmy
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  web:
    image: ghcr.io/xyphyn/photon:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      - PUBLIC_INSTANCE_URL=${DOMAIN}
      - PUBLIC_LOCK_TO_INSTANCE=${PUBLIC_LOCK_TO_INSTANCE}
    ports:
      - "172.17.0.1:9009:3000"
